# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='link',
            managers=[
                ('with_votes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=100, verbose_name=b'Headline'),
        ),
    ]
